service: web
name: job-application-tracker
env: python
root: backend
buildCommand: bash ../build.sh
startCommand: gunicorn jobtracker.wsgi --chdir . --bind 0.0.0.0:$PORT
plan: free
autoDeploy: true
healthCheckPath: /
envVars:
  - key: IS_DEPLOYED
    value: 'True'
  - key: DJANGO_SETTINGS_MODULE
    value: jobtracker.settings
